
package com.wellnessstandard.stubs;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WellnessStandardWellnessServiceSoap", targetNamespace = "http://wellness.wellnessStandard.assol.sk")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WellnessStandardWellnessServiceSoap {


    /**
     * 
     * @param yoursId
     * @param myId
     * @param cardNumber
     * @return
     *     returns com.wellnessstandard.stubs.VerifyCardReturn
     */
    @WebMethod(operationName = "verifyCard_2", action = "http://wellness.wellnessStandard.assol.sk/verifyCard_2")
    @WebResult(name = "verifyCard_2Result", targetNamespace = "http://wellness.wellnessStandard.assol.sk")
    @RequestWrapper(localName = "verifyCard_2", targetNamespace = "http://wellness.wellnessStandard.assol.sk", className = "com.wellnessstandard.stubs.VerifyCard2")
    @ResponseWrapper(localName = "verifyCard_2Response", targetNamespace = "http://wellness.wellnessStandard.assol.sk", className = "com.wellnessstandard.stubs.VerifyCard2Response")
    public VerifyCardReturn verifyCard2(
        @WebParam(name = "myId", targetNamespace = "http://wellness.wellnessStandard.assol.sk")
        long myId,
        @WebParam(name = "yoursId", targetNamespace = "http://wellness.wellnessStandard.assol.sk")
        long yoursId,
        @WebParam(name = "cardNumber", targetNamespace = "http://wellness.wellnessStandard.assol.sk")
        String cardNumber);

    /**
     * 
     * @param bill
     * @param yoursId
     * @param myId
     * @param cardNumber
     * @return
     *     returns int
     */
    @WebMethod(operationName = "sendBillCard_1", action = "http://wellness.wellnessStandard.assol.sk/sendBillCard_1")
    @WebResult(name = "sendBillCard_1Result", targetNamespace = "http://wellness.wellnessStandard.assol.sk")
    @RequestWrapper(localName = "sendBillCard_1", targetNamespace = "http://wellness.wellnessStandard.assol.sk", className = "com.wellnessstandard.stubs.SendBillCard1")
    @ResponseWrapper(localName = "sendBillCard_1Response", targetNamespace = "http://wellness.wellnessStandard.assol.sk", className = "com.wellnessstandard.stubs.SendBillCard1Response")
    public int sendBillCard1(
        @WebParam(name = "myId", targetNamespace = "http://wellness.wellnessStandard.assol.sk")
        long myId,
        @WebParam(name = "yoursId", targetNamespace = "http://wellness.wellnessStandard.assol.sk")
        long yoursId,
        @WebParam(name = "cardNumber", targetNamespace = "http://wellness.wellnessStandard.assol.sk")
        String cardNumber,
        @WebParam(name = "bill", targetNamespace = "http://wellness.wellnessStandard.assol.sk")
        Bill bill);

    /**
     * 
     * @param test
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://wellness.wellnessStandard.assol.sk/test")
    @WebResult(name = "testResult", targetNamespace = "http://wellness.wellnessStandard.assol.sk")
    @RequestWrapper(localName = "test", targetNamespace = "http://wellness.wellnessStandard.assol.sk", className = "com.wellnessstandard.stubs.Test")
    @ResponseWrapper(localName = "testResponse", targetNamespace = "http://wellness.wellnessStandard.assol.sk", className = "com.wellnessstandard.stubs.TestResponse")
    public String test(
        @WebParam(name = "test", targetNamespace = "http://wellness.wellnessStandard.assol.sk")
        String test);

    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod(action = "http://wellness.wellnessStandard.assol.sk/getVersion")
    @WebResult(name = "getVersionResult", targetNamespace = "http://wellness.wellnessStandard.assol.sk")
    @RequestWrapper(localName = "getVersion", targetNamespace = "http://wellness.wellnessStandard.assol.sk", className = "com.wellnessstandard.stubs.GetVersion")
    @ResponseWrapper(localName = "getVersionResponse", targetNamespace = "http://wellness.wellnessStandard.assol.sk", className = "com.wellnessstandard.stubs.GetVersionResponse")
    public int getVersion();

}
